sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install ."
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - "pip install coveralls"
script:
  - coverage run setup.py test
after_success:
  - coveralls
  - coverage report
deploy:
  provider: pypi
  user: gisce
  password:
    secure: mxWzYVAFP/JgavnLxT3jvHno6+8ItIDaXJ3IWts+uqxNEVxZ1bcv2NR/sj/CbHiCz+52nRIpcfHCOx4hv4RtS3WGWz+SS/DOLSPgUGFrlpI2wMOWKHQYQMlES6wHqfVx01+HZCIqHED0ArB76QkPItKjPpe9bxtZ8/tiXXrfFkW77sRGInqqHK8A7exT+E5Y+ZgZME3BdJzljyIx1qEQZLWv299j95rvFD2rheo3m/I7r6dAdYTAbjkkCf7IgcfOzHuIVENbYNgrPMEOnPHISj2BwCKHoPHJGG3C9R73njEKV9frJXNv6pCd8Ib5trejoGM/5bcIvToQgsoURYWI8qi/FRTDAkC/TOk2VtnMAGuq70wHK8SfM5SPLm6nR8fJsEOFsa2EYdf5ocyosgquFUgcPSmy1A0NnWYz6j1JChhrhRzXZ6oS9lLaYcw7qBdUdIjA5HMfNaRJd75SzlgUOI2MrApRQgvgV90cA5y8bnQ47Xgn+aomR5TA3dhgVl8XewOI340iJ/MdUYDh0nQm6j0lUD77upI+PHcLajP0htkWWIa2tMo61zWvDkXhahRgCywULAqnxNmtEfv9m0YkUEzV077LdR+G7s9vFoIwwfFH/fsPdAMek8j/QLLY4MC9PEGFXbnQVWTkdwT5PbQUgPC81oIsX9Ov48bL2r/qK2o=
  on:
    tags: true
    repo: gisce/switching
