sudo: false
language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
script:
  - python setup.py test
notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK
    on_success: always
    on_failure: always
    on_start: true
