sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install ."
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - "pip install coveralls"
script:
  - coverage run setup.py test
after_success:
  - coveralls
  - coverage report
